global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "todolist-api-prod"
    metrics_path: "/internal/actuator/prometheus"
    static_configs:
      - targets: ["spring_app:8080"]
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        regex: (.+):8082
        target_label: instance
        replacement: $1
